### ISSUE TITLE
Symlinked scripts are not recognized

### ISSUE THREAD

**Issue by jindrichmynarz** [OpenDataNode/UVPlugin-executeShellScript#2]
The DPU does not recognize symbolic links. For example, I have a script symlinked from `/usr/bin/uvunzip`. If I just pass `uvunzip` as the script name to the DPU, the following error is raised:

```
Execution failed because: Given script doesnt exixst.eu.unifiedviews.dpu.DPUException: Given script doesnt exixst.
at eu.unifiedviews.helpers.dpu.context.ContextUtils.dpuException(ContextUtils.java:181)
at eu.comsode.unifiedviews.plugins.extractor.executeshellscript.ExecuteShellScript.innerExecute(ExecuteShellScript.java:64)
at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:117)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452)
at java.lang.Thread.run(Thread.java:745)
```

If I provide the absolute path to the script, then it works.

Based on discussion with @skrchnavy, this is a bug, not a feature. This issue is split from #1.

Additionally, @skrchnavy writes that "script location shall be configurable with default in UV workspace".

**Comment by skrchnavy** [comment]
DPU relocated, issue tracked there as: UnifiedViews/Plugins#330
